global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"    # Можно добавить файлы с правилами алертинга
  # - "second_rules.yml"

scrape_configs:
  # КОНФИГУРАЦИЯ СБОРА МЕТРИК
  - job_name: 'prometheus'
    # Job 1: Мониторинг самого Prometheus
    static_configs:
      labels:
        - targets: ['localhost:9090'] # Prometheus мониторит сам себя
          app: 'prometheus'

  - job_name: 'fin-u-ch-api'
    # Мониторинг запросов
    static_configs:
      - targets: ['api:4000']
        labels:
          app: 'fin-uch'
