global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"    # ����� �������� ����� � ��������� ���������
  # - "second_rules.yml"

scrape_configs:
  # ������������ ����� ������

  # Job 1: ���������� ������ Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus ��������� ��� ����
        labels:
          app: 'prometheus'

  # ���������� ��������
  - job_name: 'fin-u-ch-api'
    static_configs:
      - targets: ['api:4000']
        labels:
          app: 'fin-uch'
